services:
  - type: web
    name: rrc-api
    env: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MYSQL_HOST
        value: rrc-lights-sounds-rrc.l.aivencloud.com
      - key: MYSQL_PORT
        value: "28839"
      - key: MYSQL_USER
        value: avnadmin
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        value: defaultdb
      - key: MYSQL_SSL
        value: "true"
      - key: EMAIL_SERVICE
        value: gmail
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: SKIP_EMAIL_VERIFICATION
        value: "false"
      - key: CORS_ORIGINS
        value: https://rrc-client.vercel.app
